---
title: "MechaCarChallenge"
output: html_notebook
---

DELIVERABLE 1: Linear Regression to Predict MPG

```{r}
# Step 3: Library for dplyr package
library(dplyr)
```
```{r}
# Step 4: Import and read the csv file
car_table <- read.csv('MechaCar_mpg.csv',check.names = F,stringsAsFactors = F)
class(car_table)
```
```{r}
# Setp 5: Perform linear function
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, car_table) #generate multiple linear regression model
```

```{r}
# Step 6: determine the p-value and the r-squared value for the linear regression model
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, car_table)) #generate summary statistics
```

Deliverable 2: Create Visualizations for the Trip Analysis

```{r}
# Step 2: Import and read the csv file
coil_table <- read.csv('Suspension_Coil.csv',stringsAsFactors = F)
class(coil_table)
```

```{r}
# Step 3: Write an RScript that creates a total_summary dataframe using the summarize() function to get the mean, median, variance, and standard deviation of the suspension coil’s PSI column.
total_summary <- coil_table %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI)) 
print(total_summary)
```


```{r}
# Step 4: Write an RScript that creates a lot_summary dataframe using the group_by() and the summarize() functions to group each manufacturing lot by the mean, median, variance, and standard deviation of the suspension coil’s PSI column.
lot_summary <- coil_table %>% group_by(Manufacturing_Lot) %>% 
              summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
print(lot_summary)
```

DELIVERABLE 3: T-Tests on Suspension Coils

```{r}
# Step 1: write an RScript using the t.test() function to determine if the PSI across all manufacturing lots is statistically different from the population mean of 1,500 pounds per square inch

t.test(x=coil_table$PSI,mu=1500) #compare sample versus population means

```

```{r}
# Step 2: write three more RScripts in your MechaCarChallenge.RScript using the t.test() function and its subset() argument to determine if the PSI for each manufacturing lot is statistically different from the population mean of 1,500 pounds per square inch
# Subset for lot 1

pop1 <- subset(coil_table, Manufacturing_Lot=='Lot1') 
t.test(x=pop1$PSI, mu=1500) 

```

```{r}
# Subset and t test for lot 2

pop2 <- subset(coil_table, Manufacturing_Lot=='Lot2') 
t.test(x=pop1$PSI, mu=1500) 

```

```{r}
# Subset and t test for lot 3

pop3 <- subset(coil_table, Manufacturing_Lot=='Lot3') 
t.test(x=pop1$PSI, mu=1500) 

```

